services:
  - type: web
    name: gold-dollar-bot
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: GOLD_BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: CHANNEL_USERNAME
        sync: false
      - key: PORT
        value: "10000"
      - key: NODE_VERSION
        value: "20"
