'use strict';

/* ============================================================
   📚 بانک پرامپت‌های تصویری (کاملاً آفلاین)
   ------------------------------------------------------------
   هر پرامپت: { id, cat, t (عنوان فارسی), tip (نکته فارسی), prompt (انگلیسی) }
   برای اضافه‌کردن پرامپت جدید در ربات: /addprompt عنوان فارسی | نکته | پرامپت انگلیسی
   ============================================================ */

const CATEGORIES = [
  { id: 'portrait',   fa: 'پرتره و عکس پرسنلی', emoji: '👤' },
  { id: 'avatar',     fa: 'آواتار و پروفایل',    emoji: '🙂' },
  { id: 'fantasy',    fa: 'فانتزی و افسانه‌ای',    emoji: '🧝' },
  { id: 'anime',      fa: 'انیمه و مانگا',       emoji: '🌸' },
  { id: 'cartoon',    fa: 'کارتونی و بامزه',     emoji: '🧸' },
  { id: 'logo',       fa: 'لوگو و برندینگ',      emoji: '✒️' },
  { id: 'poster',     fa: 'پوستر و تایپوگرافی',  emoji: '🖼️' },
  { id: 'product',    fa: 'عکس محصول',          emoji: '📦' },
  { id: 'food',       fa: 'غذا و نوشیدنی',       emoji: '🍕' },
  { id: 'scifi',      fa: 'علمی‑تخیلی',          emoji: '🚀' },
  { id: 'cyberpunk',  fa: 'سایبرپانک و نئون',    emoji: '🌃' },
  { id: 'render3d',   fa: 'رندر سه‌بعدی و مینیمال', emoji: '🧊' },
  { id: 'nature',     fa: 'طبیعت و منظره',      emoji: '🏞️' },
  { id: 'persian',    fa: 'ایرانی و سنتی',       emoji: '🏛️' },
  { id: 'animal',     fa: 'حیوانات',            emoji: '🐾' },
  { id: 'car',        fa: 'خودرو',              emoji: '🚗' },
  { id: 'fashion',    fa: 'مد و لباس',          emoji: '👗' },
  { id: 'wedding',    fa: 'عروسی و عاشقانه',    emoji: '💐' },
  { id: 'sport',      fa: 'ورزشی',              emoji: '⚽' },
  { id: 'painting',   fa: 'نقاشی و هنر دستی',    emoji: '🖌️' },
  { id: 'arch',       fa: 'معماری و دکوراسیون',  emoji: '🏠' },
  { id: 'kidsbook',   fa: 'کتاب کودک',          emoji: '📚' },
  { id: 'infographic', fa: 'اینفوگرافیک و نمودار', emoji: '📊' },
  { id: 'misc',       fa: 'عمومی و خلاقانه',     emoji: '🎨' },
];

const Q = 'ultra detailed, sharp focus, professional photography, high dynamic range, 8k';

const PROMPTS = [
  /* ───────────── 👤 پرتره ───────────── */
  { id: 'po1', cat: 'portrait', t: 'پرتره استودیویی کلاسیک',
    tip: 'زمانی که پرامپت را تست می‌کنی، کلمه‌ی 45mm را به 85mm تغییر بده تا فشرده‌سازی صورت نرم‌تر شود.',
    prompt: `Cinematic studio portrait of a confident young woman in a beige blazer, soft octabox key light from the left, gentle rim light, seamless charcoal backdrop, 85mm lens, shallow depth of field, natural skin texture, muted color grading, ${Q}` },
  { id: 'po2', cat: 'portrait', t: 'پرتره نور پنجره',
    tip: 'برای حس صمیمی‌تر، «soft window light» را با «golden hour light» عوض کن.',
    prompt: `Environmental portrait of an elderly craftsman sitting in his workshop, warm daylight streaming through a dusty window, wood shavings in the air, weathered expressive hands, documentary style, 50mm lens, Kodak Portra color science, ${Q}` },
  { id: 'po3', cat: 'portrait', t: 'پرتره سیاه‌وسفید درام',
    tip: 'اگر نتیجه زیادی تیره شد، در انتهای پرامپت «exposure +0.5 stop» را اضافه کن.',
    prompt: `High contrast black and white portrait of an athlete after training, sweat and steam, dramatic side light, deep shadows, freckles and pores visible, editorial sports magazine style, 105mm lens, fine film grain, ${Q}` },
  { id: 'po4', cat: 'portrait', t: 'پرتره عکاسی پرسنلی لینکدین',
    tip: 'رنگ پس‌زمینه را عوض کن: «seamless white backdrop» یا «soft gradient teal backdrop».',
    prompt: `Corporate headshot of a smiling man with short dark hair and glasses, crisp navy suit, three point lighting, seamless light gray backdrop, symmetrical framing, editorial business magazine quality, 85mm lens, transparent skin detail, ${Q}` },
  { id: 'po5', cat: 'portrait', t: 'پرتره رنگ روغن دیجیتال',
    tip: 'برای بافت نقاشی واقعی‌تر «visible canvas texture» را به انتها اضافه کن.',
    prompt: `Digital oil painting portrait of a woman with flowers woven into her braided hair, loose expressive brush strokes, thick impasto highlights, warm ochre and rose palette, Rembrandt lighting, gallery quality canvas texture, ${Q}` },
  { id: 'po6', cat: 'portrait', t: 'پرتره با کنتراست رنگی',
    tip: 'دو رنگ مکمل را در پرامپت عوض کن تا پالت تازه بگیری (مثلاً سبز و نارنجی).',
    prompt: `Portrait of a musician lit by a magenta and cyan gel setup, haze in the air, leather jacket, confident gaze at camera, dark studio, hard light with soft falloff, editorial music photography, 70-200mm at f2, ${Q}` },

  /* ───────────── 🙂 آواتار ───────────── */
  { id: 'av1', cat: 'avatar', t: 'آواتار سه‌بعدی پیکسار',
    tip: 'برای ست‌شدن با پروفایل، در پایان «centered square composition» را اضافه کن.',
    prompt: `Cute stylized 3D avatar of a young man with curly hair and a hoodie, Pixar style, oversized expressive eyes, soft studio lighting, pastel gradient background, subsurface scatter on skin, centered square composition, octane render, ${Q}` },
  { id: 'av2', cat: 'avatar', t: 'آواتار مینیمال فلت',
    tip: 'آواتار فلت برای لوگو و پروفایل کسب‌وکار عالیه؛ رنگ برند خودت را جایگزین کن.',
    prompt: `Minimal flat vector avatar of a bearded developer with round glasses, geometric shapes, limited two color palette, subtle noise texture, clean negative space, modern dribbble style, perfectly centered, ${Q}` },
  { id: 'av3', cat: 'avatar', t: 'آواتار گربه فضانورد',
    tip: 'نژاد گربه و رنگ لباس را عوض کن تا صد نسخه‌ی متفاوت بگیری.',
    prompt: `Adorable chubby cat astronaut floating in space, glossy white suit with orange stripes, tiny helmet reflection of a planet, big curious eyes, cinematic soft lighting, playful narrative illustration, centered avatar framing, ${Q}` },
  { id: 'av4', cat: 'avatar', t: 'آواتار پروفایل نئون',
    tip: 'برای تم دسکتاپ، «neon cyan» را با «neon purple» عوض کن.',
    prompt: `Profile avatar of a hooded figure silhouette against neon cyan grid, subtle glitch effect, volumetric fog, retro synthwave palette, high contrast, perfectly symmetrical square crop, digital illustration, ${Q}` },
  { id: 'av5', cat: 'avatar', t: 'آواتار گل و بوته',
    tip: 'اگر برای چاپ می‌خواهی، در انتها «transparent background» اضافه کن.',
    prompt: `Elegant avatar of a woman's profile formed from flowing botanical leaves and roses, single continuous line art with colored fills, gold accents, cream background, luxury brand identity style, centered composition, ${Q}` },

  /* ───────────── 🧝 فانتزی ───────────── */
  { id: 'fa1', cat: 'fantasy', t: 'الف جنگل تاریک',
    tip: 'با تغییر «autumn forest» به «frozen forest» حال‌وهوای زمستانی می‌گیری.',
    prompt: `Ethereal elven archer standing on a mossy rock in an ancient autumn forest, silver braided hair, glowing runes on her leather armor, volumetric god rays through golden leaves, fantasy concept art, ArtStation trending, ${Q}` },
  { id: 'fa2', cat: 'fantasy', t: 'دروازه غول‌آسای افسانه‌ای',
    tip: 'برای حس حماسی انسانی، در ابتدای پرامپت «tiny human traveler» را اضافه کن.',
    prompt: `Colossal ancient stone gate carved with forgotten runes, floating islands chained to the gate, waterfalls pouring into clouds, lone wanderer with a lantern for scale, epic fantasy matte painting, golden hour, ${Q}` },
  { id: 'fa3', cat: 'fantasy', t: 'اژدها روی برج',
    tip: 'رنگ اژدها را عوض کن تا شخصیت شریر یا مقدس بسازی (بنفش = جادویی).',
    prompt: `Majestic emerald dragon perched on a crumbling cathedral spire, torn banners in the wind, storm clouds parting above, scales catching cold moonlight, epic fantasy key art, dramatic low angle, ${Q}` },
  { id: 'fa4', cat: 'fantasy', t: 'جادوگر در کتابخانه',
    tip: 'برای نورپردازی جادویی «floating glowing runes» را به انتها اضافه کن.',
    prompt: `Young sorceress studying in an endless candle-lit library, floating books orbiting her hands, glowing arcane sigils, dust motes in beams of light, deep teal and amber palette, cinematic fantasy illustration, ${Q}` },
  { id: 'fa5', cat: 'fantasy', t: 'شهر زیر آب پریان',
    tip: 'برای تاریکی و رمز، «bioluminescent» را به «sunlit» تغییر بده.',
    prompt: `Underwater fairy city built from mother of pearl shells, bioluminescent corals, jellyfish lanterns, mermaid swimming through arched streets, caustic light rays from the surface, dreamy fantasy concept art, ${Q}` },
  { id: 'fa6', cat: 'fantasy', t: 'شمشیر افسانه‌ای در سنگ',
    tip: 'پس‌زمینه را به «volcanic wasteland» تغییر بده تا حس پایان‌الزمانی بسازی.',
    prompt: `Legendary sword embedded in a cracked ancient boulder, glowing runes along the blade, misty mountain valley at dawn, fireflies, hopeful warm backlight, epic fantasy promotional art, shallow depth of field, ${Q}` },

  /* ───────────── 🌸 انیمه ───────────── */
  { id: 'an1', cat: 'anime', t: 'دختر انیمه زیر باران نئون',
    tip: 'رنگ چتر را عوض کن تا تضاد رنگی تازه بسازی (زرد روی بنفش خیلی جذاب می‌شه).',
    prompt: `Anime girl with silver twin tails holding a transparent umbrella in a rainy neon Shibuya alley, reflections on wet asphalt, cinematic rim light, cel shaded, Studio Ghibli meets Makoto Shinkai, volumetric rain, ${Q}` },
  { id: 'an2', cat: 'anime', t: 'قهرمان انیمه با شمشیر',
    tip: 'برای حالت اکشن، «dynamic motion blur» را اضافه کن.',
    prompt: `Determined anime swordsman mid-slash, glowing katana trail, cherry blossom petals scattered by the shockwave, traditional shrine background, dynamic action composition, bold line art, dramatic sunset palette, ${Q}` },
  { id: 'an3', cat: 'anime', t: 'قطار شب انیمه',
    tip: 'این پرامپت برای تصویرسازی جلد موسیقی و پروفایل بی‌نظیره.',
    prompt: `Lone anime student waiting on an empty rural train platform at night, vending machine glow, single streetlamp, distant city lights, nostalgic summer night mood, Shinkai style, soft film grain, wide cinematic frame, ${Q}` },
  { id: 'an4', cat: 'anime', t: 'گربه انیمه در آشپزخانه',
    tip: 'برای نسخه‌ی بامزه‌تر «chibi proportions» را اضافه کن.',
    prompt: `Chibi anime cat chef flipping an omelet in a cozy tiny kitchen, steam swirls, warm morning light through lace curtains, pastel colors, expressive sparkle eyes, wholesome slice of life illustration, ${Q}` },
  { id: 'an5', cat: 'anime', t: 'مکا در شهر آینده',
    tip: 'برای حس مانگای قدیمی «90s retro anime aesthetic» را جایگزین کن.',
    prompt: `Giant mecha standing among skyscrapers at sunrise, pilot silhouette in the foreground, lens flare, detailed mechanical greebles, anime key visual, vibrant sky with dramatic clouds, epic scale, ${Q}` },

  /* ───────────── 🧸 کارتونی ───────────── */
  { id: 'ca1', cat: 'cartoon', t: 'دوستانه‌های پیکساری',
    tip: 'برای انیمیشن کوتاه، همین پرامپت را با «same character, different pose» تکرار کن.',
    prompt: `Pixar style 3D character of a clumsy baker fox in a striped apron, flour explosion mid-air, warm bakery interior, big expressive eyes, soft global illumination, joyful cinematic lighting, adorable exaggeration, ${Q}` },
  { id: 'ca2', cat: 'cartoon', t: 'تصویرسازی کودکانه‌ی آبرنگی',
    tip: 'کاغذ بافت‌دار و رنگ‌های پاستلی، حس کتاب کودک می‌سازد.',
    prompt: `Watercolor children's book illustration of three friends rowing a paper boat down a rainy street, soft pastel palette, visible paper texture, gentle ink outlines, whimsical and warm storytelling mood, ${Q}` },
  { id: 'ca3', cat: 'cartoon', t: 'دایناسور مهربان',
    tip: 'برای نسخه‌ی مغازه‌داری، «shopkeeper dino with tiny hat» را امتحان کن.',
    prompt: `Friendly rounded dinosaur baking cookies in a cottage kitchen, flour on his snout, tiny chef hat, cozy yellow light, stylized 3D cartoon render, soft shadows, whimsical and heartwarming, ${Q}` },
  { id: 'ca4', cat: 'cartoon', t: 'استیکر خنده‌دار',
    tip: 'برای استیکر تلگرام، در انتها «plain white background, thick outline» بگذار.',
    prompt: `Funny cartoon sticker of a sleepy office cat spilling coffee on its laptop, exaggerated shocked expression, bold thick outlines, flat colors, plain white background, sticker sheet style, ${Q}` },
  { id: 'ca5', cat: 'cartoon', t: 'روبوی بامزه در گل‌فروشی',
    tip: 'برای پالت تازه، «spring flowers» را با «tulips and sunflowers» عوض کن.',
    prompt: `Tiny rusty robot carefully watering spring flowers in a glass greenhouse, birds perched on its head, warm afternoon light, cinematic 3D cartoon render, charming character design, shallow depth of field, ${Q}` },

  /* ───────────── ✒️ لوگو ───────────── */
  { id: 'lo1', cat: 'logo', t: 'لوگوی مینیمال طلایی',
    tip: 'به‌جای «fox» نماد کسب‌وکار خودت را بگذار (مثل cup, leaf, cube, arrow).',
    prompt: `Minimal geometric logo of an abstract fox head built from three triangles, gold gradient on deep charcoal background, luxury brand mark, negative space, symmetrical, vector clean edges, ${Q}` },
  { id: 'lo2', cat: 'logo', t: 'لوگوی کافه با خط دست',
    tip: 'برای لوگوی شیک‌تر «hand-drawn line art, single continuous stroke» را اضافه کن.',
    prompt: `Hand-drawn logo mark for a specialty coffee house: a coffee cherry branch forming a cup silhouette, single continuous line, warm brown on cream, vintage stamp texture, balanced and memorable, ${Q}` },
  { id: 'lo3', cat: 'logo', t: 'لوگوی تکنولوژی گرادیانی',
    tip: 'برای هویت استارتاپ‌ها عالیه؛ رنگ گرادیان را به سبز‑آبی عوض کن تا تم فین‌تک بگیری.',
    prompt: `Modern tech startup logo: abstract letter N formed by a continuous ribbon, vibrant violet to cyan gradient, flat vector style, subtle 3D bevel, clean white background, scalable app icon, ${Q}` },
  { id: 'lo4', cat: 'logo', t: 'لوگوی طلایی لوکس با مونوگرام',
    tip: 'حرف اول برند خودت را جای M بگذار.',
    prompt: `Luxury monogram logo letter M with art deco geometry, brushed gold foil texture, elegant thin serifs, dark green marble background, premium hospitality brand identity, symmetrical crest, ${Q}` },
  { id: 'lo5', cat: 'logo', t: 'لوگوی سه‌بعدی کلی',
    tip: 'برای اپ موبایل، «app icon 1024x1024, rounded square» را اضافه کن.',
    prompt: `Glossy 3D app icon of a smiling chat bubble and a rocket, soft clay material, pastel blue and coral, studio reflections, subtle shadow, modern mobile app branding, centered composition, ${Q}` },

  /* ───────────── 🖼️ پوستر ───────────── */
  { id: 'ps1', cat: 'poster', t: 'پوستر سینمایی مینیمال',
    tip: 'متن را با متن دلخواه خودت عوض کن؛ برای پوستر فارسی، عبارت انگلیسی را نگه دار.',
    prompt: `Minimal movie poster design: lone silhouette standing before a giant glowing circle, negative space typography area at the top, retro print grain, two color palette of deep blue and orange, award-winning art direction, ${Q}` },
  { id: 'ps2', cat: 'poster', t: 'پوستر کنسرت نئون',
    tip: 'برای موسیقی الکترونیک، «glitch scanlines» را اضافه کن.',
    prompt: `Concert poster with a figure silhouetted against laser beams, bold distorted headline space, neon pink and cyan on black, halftone texture, brutalist grid layout, energetic music event advertising, ${Q}` },
  { id: 'ps3', cat: 'poster', t: 'پوستر تایپوگرافی عربی‑فارسی',
    tip: 'اگر می‌خواهی متن دقیق باشد، متن نهایی را در برنامه‌ی طراحی روی خروجی بنویس.',
    prompt: `Typographic poster featuring flowing Persian Nastaliq calligraphy rearranged into a spiral, gold ink on deep indigo paper, subtle paper fiber texture, contemporary middle eastern graphic design, ${Q}` },
  { id: 'ps4', cat: 'poster', t: 'پوستر ورزشی حماسی',
    tip: 'برای فینال لیگ، رنگ‌های تیم خودت را جایگزین کن.',
    prompt: `Epic sports poster of a football player frozen mid-bicycle-kick, particles of grass and sweat, dramatic backlight, dark stadium background, bold diagonal composition, championship energy, ${Q}` },
  { id: 'ps5', cat: 'poster', t: 'پوستر سلامت و آرامش',
    tip: 'برای برند اسپا و یوگا عالی است؛ می‌توانی «watercolor wash» اضافه کنی.',
    prompt: `Wellness poster design: woman meditating, her breath turning into flowing botanical linework, soft sage green and cream palette, generous negative space, calm modern editorial art direction, ${Q}` },

  /* ───────────── 📦 عکس محصول ───────────── */
  { id: 'pr1', cat: 'product', t: 'عکس محصول لوکس روی سنگ',
    tip: 'به‌جای «perfume bottle» محصول خودت را بگذار تا رندر تبلیغاتی بگیری.',
    prompt: `Luxury perfume bottle on a wet dark marble slab, golden liquid, dramatic single spotlight, mist and droplets, reflections, macro detail, high end advertising product photography, 100mm macro lens, ${Q}` },
  { id: 'pr2', cat: 'product', t: 'عکس محصول شناور',
    tip: 'برای تبلیغ اینستاگرام «dynamic splash» حال‌وهوای تبلیغاتی می‌سازد.',
    prompt: `Skincare serum bottle floating above rippling water, splash frozen mid-air, soft gradient turquoise background, fresh botanical leaves, clean commercial lighting, centered hero product shot, ${Q}` },
  { id: 'pr3', cat: 'product', t: 'هدفون روی میز مینیمال',
    tip: 'برای عکس بنر سایت، «wide banner composition» را اضافه کن.',
    prompt: `Premium over-ear headphones on a minimal concrete pedestal, single soft gradient light, deep shadows, subtle colored rim light, technology product advertising, ultra clean composition, macro texture detail, ${Q}` },
  { id: 'pr4', cat: 'product', t: 'عکس مدل با محصول',
    tip: 'برای صفحه‌ی فروشگاه، «plain seamless backdrop» را نگه دار.',
    prompt: `Lifestyle product shot: hand holding a matte black smartwatch against a soft beige backdrop, natural window light, minimal jewelry styling, shallow depth of field, editorial e-commerce photography, ${Q}` },
  { id: 'pr5', cat: 'product', t: 'بسته‌بندی قهوه با طراحی دستی',
    tip: 'رنگ بسته را با رنگ برند خودت هماهنگ کن.',
    prompt: `Artisan coffee bag packaging mockup on a rustic wooden counter, kraft paper with bold geometric label, scattered roasted beans, warm morning light, small local brand aesthetic, top-down hero shot, ${Q}` },

  /* ───────────── 🍕 غذا ───────────── */
  { id: 'fo1', cat: 'food', t: 'پیتزای پنیری با کشش',
    tip: 'با تغییر «pepperoni» به «margherita with basil» نسخه‌ی ایتالیایی بساز.',
    prompt: `Close-up of a hot pepperoni pizza slice being lifted, molten cheese stretching, basil and chili flakes, steam, dark rustic wooden table, moody warm restaurant lighting, food photography, 50mm macro, ${Q}` },
  { id: 'fo2', cat: 'food', t: 'کیک شکلاتی آبرومند',
    tip: 'برای حس دلچسب‌تر «pouring warm ganache» را اضافه کن.',
    prompt: `Decadent dark chocolate layer cake on a ceramic stand, glossy ganache drip, cocoa dust in the air, crushed pistachios, dark moody background, styled dessert photography, soft directional light, ${Q}` },
  { id: 'fo3', cat: 'food', t: 'چای ایرانی و شیرینی',
    tip: 'برای تم نوروز، «with a small goldfish bowl and sprouted wheat» را اضافه کن.',
    prompt: `Persian tea ceremony still life: estekan glass of amber tea on a saucer, crystal sugar cubes, baklava and fresh dates on a brass tray, handmade kilim textile, warm nostalgic window light, ${Q}` },
  { id: 'fo4', cat: 'food', t: 'کاپوچینو مینیمال',
    tip: 'برای کافه‌شاپ، «latte art heart» را به «swan» تغییر بده.',
    prompt: `Overhead shot of a cappuccino with perfect latte art on a textured concrete table, ceramic cup, croissant crumbs, morning window light, minimalistic cafe branding aesthetic, natural tones, ${Q}` },
  { id: 'fo5', cat: 'food', t: 'کباب و سفره ایرانی',
    tip: 'برای رستوران سنتی عالیه؛ «flame and smoke» حس واقعی می‌دهد.',
    prompt: `Juicy Persian kebab skewers grilling over glowing charcoal, flames and smoke, saffron rice, grilled tomato and sumac in the corner, rustic copper tray, dramatic warm fire light, appetizing food photography, ${Q}` },

  /* ───────────── 🚀 علمی‑تخیلی ───────────── */
  { id: 'sc1', cat: 'scifi', t: 'سیاره ناشناخته',
    tip: 'برای حس تنهایی، در ابتدا «lone astronaut» را اضافه کن.',
    prompt: `Alien desert planet with giant ringed gas giant in the sky, crystalline rock formations, two astronauts walking with rover, purple and amber atmosphere, hard sci-fi concept art, wide cinematic vista, ${Q}` },
  { id: 'sc2', cat: 'scifi', t: 'ایستگاه فضایی مدرن',
    tip: 'برای فرم فیلم، «volumetric lighting» و «lens flare» را اضافه کن.',
    prompt: `Interior of a modern orbital space station observation deck, Earth glowing through a huge curved window, sleek white panels and holographic UI, crew silhouettes, cool blue light and warm console accents, ${Q}` },
  { id: 'sc3', cat: 'scifi', t: 'مکا مینیاتوری رزینی',
    tip: 'برای نمونه‌ی چاپ سه‌بعدی، «toy photography on black acrylic» بگذار.',
    prompt: `Hyper detailed battle mech miniature standing on a ruined city diorama, weathered paint chipping, glowing cockpit, macro toy photography, dramatic rim lighting, shallow depth of field, ${Q}` },
  { id: 'sc4', cat: 'scifi', t: 'کاوشگر در سیاه‌چال',
    tip: 'برای بازی ویدیویی، «game key art with empty space for logo» اضافه کن.',
    prompt: `Futuristic rover descending into a glowing crystal cavern on an alien moon, bioluminescent plants, mist, headlights cutting through fog, exploration adventure sci-fi key art, dramatic scale, ${Q}` },
  { id: 'sc5', cat: 'scifi', t: 'سفینه در سحابی',
    tip: 'برای والپیپر موبایل، «vertical composition» را اضافه کن.',
    prompt: `Sleek exploration starship drifting through a colorful nebula, hull catching starlight, distant sun flare, dust and gas clouds in teal and magenta, cinematic space opera illustration, sense of wonder, ${Q}` },

  /* ───────────── 🌃 سایبرپانک ───────────── */
  { id: 'cy1', cat: 'cyberpunk', t: 'خیابان بارانی سایبرپانک',
    tip: 'برای حس فیلم بلید رانر، «heavy atmosphere haze» را اضافه کن.',
    prompt: `Cyberpunk street scene after rain, towering holographic advertisements in Japanese and Korean, wet asphalt mirrors, street vendor steam, neon pink and cyan palette, anamorphic lens flare, ${Q}` },
  { id: 'cy2', cat: 'cyberpunk', t: 'هاکر در اتاق تاریک',
    tip: 'برای تم تیره‌تر، نور را فقط به مانیتورها محدود کن.',
    prompt: `Hacker in a dark apartment plastered with screens, code and neon kanji reflected on their face, cables and coffee cups, cyan and magenta monitor glow, moody cinematic still, ${Q}` },
  { id: 'cy3', cat: 'cyberpunk', t: 'ماشین پرنده بالای شهر',
    tip: 'برای حس ۸۰ ویدیو، «synthwave grid reflections» را اضافه کن.',
    prompt: `Flying car weaving between megacity skyscrapers at night, endless neon signage below, rain streaks, aerial cinematic shot, retro-futuristic blade runner atmosphere, dramatic scale, ${Q}` },
  { id: 'cy4', cat: 'cyberpunk', t: 'بازار شبانه آینده',
    tip: 'برای بازی نقش‌آفرینی، «vibrant crowd, motion blur» را اضافه کن.',
    prompt: `Bustling futuristic night market alley, holographic food stalls, steam and smoke, glowing lanterns, cybernetically enhanced shoppers, layered depth, cinematic cyberpunk concept art, ${Q}` },
  { id: 'cy5', cat: 'cyberpunk', t: 'پرتره سایبرنتیک',
    tip: 'برای جلد آلبوم، با «square crop, bold negative space» ترکیب کن.',
    prompt: `Close-up portrait of a woman with subtle cybernetic implants and glowing eye lens, chrome hair clips, neon reflections on skin, dark background with bokeh signs, cinematic sci-fi beauty shot, ${Q}` },

  /* ───────────── 🧊 رندر سه‌بعدی ───────────── */
  { id: 'r31', cat: 'render3d', t: 'رندر مینیمال ایزومتریک',
    tip: 'برای بنر سایت و اینفوگرافیک عالیه؛ رنگ‌ها را با برند خودت هماهنگ کن.',
    prompt: `Isometric minimal 3D render of a small workspace: desk, laptop, plant, coffee cup, soft clay materials, pastel palette, clean studio lighting, subtle ambient occlusion, trending CGI style, ${Q}` },
  { id: 'r32', cat: 'render3d', t: 'کره‌های شیشه‌ای رنگی',
    tip: 'برای والپیپر ۴K، «super clean background, perfect reflections» بگذار.',
    prompt: `Abstract 3D render of glossy glass spheres and flowing chrome ribbons on a soft gradient background, iridescent refractions, studio HDRI lighting, minimal composition, commercial CGI quality, ${Q}` },
  { id: 'r33', cat: 'render3d', t: 'شخصیت خمیری مینیمال',
    tip: 'برای استیکر یا آواتار تیمی، «simple shapes, tiny eyes» حس بامزه می‌دهد.',
    prompt: `Cute clay 3D character with simple rounded shapes, tiny dot eyes, holding a tiny laptop, soft matte material, pastel peach and mint palette, soft studio shadows, character design render, ${Q}` },
  { id: 'r34', cat: 'render3d', t: 'سازه‌ی هندسی معلق',
    tip: 'برای پیش‌نمایش پکیج، «floating on pure white» را امتحان کن.',
    prompt: `Floating geometric architecture of stacked cubes and arches, matte pastel surfaces with gold edges, soft shadows on a cream background, surreal minimal 3D art direction, ${Q}` },
  { id: 'r35', cat: 'render3d', t: 'بطری سه‌بعدی رنگی',
    tip: 'برای تم برند، نام محصول را روی بدنه بگذار (بدون متن دقیق فارسی).',
    prompt: `Stylized 3D render of a rounded cosmetic bottle with gradient glass, floating fruit slices around it, soft studio lighting, glossy reflections, playful commercial CGI, centered composition, ${Q}` },

  /* ───────────── 🏞️ طبیعت ───────────── */
  { id: 'na1', cat: 'nature', t: 'دریاچه آینه‌ای در سپیده‌دم',
    tip: 'برای چاپ دیواری، «panoramic composition» را اضافه کن.',
    prompt: `Perfectly still alpine lake at sunrise, mirror reflection of snow-capped peaks, low mist on the water, pine forest edge, pastel pink and blue sky, ultra wide landscape photography, long exposure, ${Q}` },
  { id: 'na2', cat: 'nature', t: 'کویر شبی پرستاره',
    tip: 'برای عکاسی نجومی، «milky way core, light painting foreground» بگذار.',
    prompt: `Dramatic desert dunes under the Milky Way, long exposure star trails, single dead tree silhouette, deep blue night with warm sand tones, astrophotography, ultra sharp foreground and sky, ${Q}` },
  { id: 'na3', cat: 'nature', t: 'جنگل پاییزی مه‌آلود',
    tip: 'برای حس افسانه‌ای، «tiny lantern on the path» را اضافه کن.',
    prompt: `Foggy autumn beech forest with golden leaves falling, soft god rays between trunks, mossy path, moody atmospheric depth, cinematic nature photography, muted warm palette, ${Q}` },
  { id: 'na4', cat: 'nature', t: 'آبشار پنهان در غار',
    tip: 'برای حس ماجراجویی، «light beam from a ceiling crack» اضافه کن.',
    prompt: `Hidden waterfall inside an emerald cave, turquoise pool, dripping stalactites, single beam of sunlight from a ceiling crack, lush ferns, long exposure silky water, adventure landscape photography, ${Q}` },
  { id: 'na5', cat: 'nature', t: 'مزرعه اسطوخودوس در غروب',
    tip: 'برای تبلیغ عطر و آرامش بی‌نظیره؛ «soft haze, warm rim light» بگذار.',
    prompt: `Endless lavender fields in Provence at golden hour, rows converging to a distant stone farmhouse, warm rim light on the flower tips, soft atmospheric haze, dreamy travel photography, ${Q}` },

  /* ───────────── 🏛️ ایرانی و سنتی ───────────── */
  { id: 'pe1', cat: 'persian', t: 'حیاط خانه ایرانی',
    tip: 'برای توریستی‌شدن تصویر، «tea set and poetry book on the carpet» اضافه کن.',
    prompt: `Traditional Persian courtyard house in Kashan at golden hour, turquoise tiled pool, geometric tilework walls, potted geraniums, warm lanterns, carpet and cushions in the alcove, architectural photography, ${Q}` },
  { id: 'pe2', cat: 'persian', t: 'شعر و تذهیب',
    tip: 'برای جلد کتاب، «generous margins for text» را نگه دار.',
    prompt: `Ornate Persian illuminated manuscript page: gold tazhib arabesque border, deep lapis lazuli and turquoise flourishes, subtle aged paper texture, elegant negative space for poetry, museum quality detail, ${Q}` },
  { id: 'pe3', cat: 'persian', t: 'نقش فرش ایرانی',
    tip: 'برای پکیج خبری، «flat lay of a carpet with a modern object» ترکیب جذابی می‌دهد.',
    prompt: `Macro detail of a hand-knotted Persian carpet, intricate medallion pattern in madder red, indigo and ivory, natural wool fibers visible, soft raking light revealing pile depth, luxury textile photography, ${Q}` },
  { id: 'pe4', cat: 'persian', t: 'کارگاه صنایع دستی',
    tip: 'برای مستندسازی، «artisan hands only» حس واقعی‌تری می‌دهد.',
    prompt: `Artisan hands shaping a turquoise-inlaid copper plate in an Isfahan workshop, warm tungsten light, tools and pigments scattered, dust in the air, documentary craft photography, shallow depth of field, ${Q}` },
  { id: 'pe5', cat: 'persian', t: 'کوچه قدیمی شبی مهتابی',
    tip: 'برای پوستر نوروزی، «hanging lantern and wheat sprouts» اضافه کن.',
    prompt: `Narrow old Persian alley at night, mud-brick arches, a single lantern glowing, cat on a wall, stars above, warm and cool color contrast, cinematic nostalgic Iranian cinema mood, ${Q}` },
  { id: 'pe6', cat: 'persian', t: 'میدان نقش‌جهان شبانه',
    tip: 'برای حس امروزی، «long exposure light trails» را اضافه کن.',
    prompt: `Panoramic night view of Naqsh-e Jahan square in Isfahan, illuminated blue-tiled domes and arches, wet pavement reflections, few visitors with lanterns, dramatic sky, architectural travel photography, ${Q}` },

  /* ───────────── 🐾 حیوانات ───────────── */
  { id: 'anm1', cat: 'animal', t: 'پرتره سگ با زبان بیرون',
    tip: 'نژاد را با نژاد حیوان خانگی خودت عوض کن.',
    prompt: `Playful golden retriever portrait in a field of tall grass, tongue out, ears flying, golden hour backlight rimming the fur, shallow depth of field, joyful pet photography, ${Q}` },
  { id: 'anm2', cat: 'animal', t: 'گربه روی طاقچه بارانی',
    tip: 'برای حس تنهایی دلچسب، «single raindrop on glass» را اضافه کن.',
    prompt: `Cozy black cat sitting on a rainy window ledge, droplets on the glass, blurred city lights beyond, soft warm interior light, moody cinematic pet portrait, ultra detailed fur, ${Q}` },
  { id: 'anm3', cat: 'animal', t: 'شیر در غروب ساوانا',
    tip: 'برای مستند حیات‌وحش، «dust backlight, telephoto» بگذار.',
    prompt: `Powerful male lion walking through golden savanna grass at sunset, dust glowing in backlight, intense eyes, National Geographic wildlife photography, 600mm telephoto, dramatic rim light, ${Q}` },
  { id: 'anm4', cat: 'animal', t: 'پرنده رنگین در پرواز',
    tip: 'برای عکاسی پرنده، «frozen wings, ultra fast shutter» اضافه کن.',
    prompt: `Kingfisher diving into a river, wings frozen, droplets and splash, emerald and orange plumage, dark blurred forest background, high speed wildlife photography, ultra sharp detail, ${Q}` },
  { id: 'anm5', cat: 'animal', t: 'لاک‌پشت کوچک روی خزه',
    tip: 'برای حس جادویی، «tiny mushrooms and fireflies» اضافه کن.',
    prompt: `Tiny baby turtle on a moss-covered stone, miniature ferns and dew drops, magical forest floor, soft dappled light, macro photography with dreamy bokeh, whimsical mood, ${Q}` },
  { id: 'anm6', cat: 'animal', t: 'دلفین‌ها در موج طلایی',
    tip: 'برای والپیپر، «split underwater and above water composition» را امتحان کن.',
    prompt: `Two dolphins leaping through a crystal wave at sunrise, spray backlit into gold, deep turquoise water, motion frozen at peak, marine wildlife photography, dramatic and graceful, ${Q}` },

  /* ───────────── 🚗 خودرو ───────────── */
  { id: 'car1', cat: 'car', t: 'خودرو اسپرت در پیست',
    tip: 'رنگ خودرو را عوض کن تا نمونه‌های متنوع بگیری.',
    prompt: `Matte orange sports car drifting on a wet racetrack, tire smoke and water spray, low dramatic angle, motion blur background, glossy reflections, automotive advertising photography, ${Q}` },
  { id: 'car2', cat: 'car', t: 'ماشین کلاسیک در جاده کوهستانی',
    tip: 'برای حس فیلم قدیمی، «Kodak Ektachrome look, slight grain» اضافه کن.',
    prompt: `Vintage 1967 muscle car on a coastal mountain road at golden hour, ocean cliffs and cypress trees, chrome bumpers gleaming, wide cinematic composition, film photography aesthetic, ${Q}` },
  { id: 'car3', cat: 'car', t: 'خودرو برقی آینده‌نگر',
    tip: 'برای تبلیغ فناوری، «floating light ribbons» اضافه کن.',
    prompt: `Futuristic electric concept car in a dark studio, seamless light strips along the body, cold blue accents, reflective black floor, minimal environment, high end automotive CGI render, ${Q}` },
  { id: 'car4', cat: 'car', t: 'موتور سیکلت در شب نئونی',
    tip: 'برای پوستر، «long exposure light trails behind the bike» بگذار.',
    prompt: `Cafe racer motorcycle parked in a neon lit alley at night, chrome engine reflecting pink and cyan signs, wet ground, steam from a grate, moody automotive editorial photography, ${Q}` },
  { id: 'car5', cat: 'car', t: 'آفرود در بیابان',
    tip: 'برای تبلیغ لاستیک، «close-up of spinning wheel and sand spray» را امتحان کن.',
    prompt: `Rugged 4x4 pickup truck blasting through desert dunes, sand spray backlit by the low sun, roof rack and light bar, dust cloud, dynamic action automotive photography, ${Q}` },

  /* ───────────── 👗 مد ───────────── */
  { id: 'mo1', cat: 'fashion', t: 'ادیتوریال خیابانی',
    tip: 'پالت رنگ لباس را با فصل عوض کن (پاییز: زیتونی و کاراملی).',
    prompt: `Street style editorial: model in an oversized olive trench coat crossing a rainy European street, candid motion, muted cinematic palette, 85mm bokeh background, fashion magazine aesthetic, ${Q}` },
  { id: 'mo2', cat: 'fashion', t: 'عکس لباس روی رگال',
    tip: 'برای فروشگاه آنلاین، «individually hung, price tag detail» بگذار.',
    prompt: `Minimal flat lay of a folded linen shirt and accessories on a light gray surface, soft daylight, subtle shadows, e-commerce catalog styling, neat composition with negative space, ${Q}` },
  { id: 'mo3', cat: 'fashion', t: 'استودیوی مد با نور سخت',
    tip: 'برای کمپین، «strong pose, direct gaze» حس قدرت می‌دهد.',
    prompt: `High fashion studio shot of a model in sculptural white couture, hard flash light, crisp shadows on a seamless gray backdrop, bold pose, editorial Vogue styling, medium format detail, ${Q}` },
  { id: 'mo4', cat: 'fashion', t: 'کفش روی پس‌زمینه رنگی',
    tip: 'رنگ پس‌زمینه را با رنگ محصول ست کن تا عکس کاتالوگی بسازی.',
    prompt: `Bold product fashion shot of white leather sneakers on a vivid tangerine background, hard sunlight shadow, playful color blocking, clean commercial styling, high detail texture, ${Q}` },
  { id: 'mo5', cat: 'fashion', t: 'مد سنتی مدرن‌شده',
    tip: 'برای برند ایرانی، ترکیب پارچه‌ی سنتی با کت مدرن جذاب است.',
    prompt: `Modern fashion portrait mixing Persian termeh textile with a tailored blazer, model against a warm adobe wall, soft afternoon light, cultural fusion editorial, rich textile detail, ${Q}` },

  /* ───────────── 💐 عروسی ───────────── */
  { id: 'we1', cat: 'wedding', t: 'عروسی در باغ غروب',
    tip: 'برای سفارش کارت عروسی، «soft haze and warm bokeh» عالی است.',
    prompt: `Romantic wedding couple walking through a garden at sunset, bride's veil catching the light, string lights bokeh, warm haze, elegant editorial wedding photography, backlit rim light, ${Q}` },
  { id: 'we2', cat: 'wedding', t: 'میز آماده‌ی عروسی',
    tip: 'برای رستوران و تشریفات، «candlelit tablescape» اضافه کن.',
    prompt: `Elegant wedding tablescape with white roses, gold cutlery, crystal glasses, tall candles, draped linen, soft window light, luxury event photography, symmetrical composition, ${Q}` },
  { id: 'we3', cat: 'wedding', t: 'دست‌ها و حلقه‌ها',
    tip: 'برای حس صمیمی، «soft focus on hands, tearful eyes in background» بگذار.',
    prompt: `Intimate close-up of two hands exchanging rings, delicate lace sleeve, blurred guests behind, warm documentary light, emotional wedding photojournalism, shallow depth of field, ${Q}` },
  { id: 'we4', cat: 'wedding', t: 'عکس عاشقانه‌ی مینیمال',
    tip: 'برای اینستاگرام، «square crop, muted tones» را اضافه کن.',
    prompt: `Minimal romantic photo of a couple's silhouettes against a bright sea horizon, calm pastel sky, soft film grain, quiet intimate mood, fine art wedding photography, ${Q}` },
  { id: 'we5', cat: 'wedding', t: 'دعوت‌نامه‌ی لوکس',
    tip: 'برای چاپ، «mockup with envelope and wax seal» را نگه دار.',
    prompt: `Luxury wedding invitation mockup: cream letterpress card with gold foil monogram, silk ribbon, dried florals, wax seal, styled flat lay on marble, soft daylight, ${Q}` },

  /* ───────────── ⚽ ورزشی ───────────── */
  { id: 'sp1', cat: 'sport', t: 'فوتبال در لحظه‌ی حساس',
    tip: 'برای بنر باشگاه، رنگ پیراهن را عوض کن.',
    prompt: `Footballer striking the ball mid-air, grass particles frozen, floodlight flare, packed stadium blurred behind, sweat and intensity, dynamic sports photography, low angle, ${Q}` },
  { id: 'sp2', cat: 'sport', t: 'بسکتبال زیر نور سالن',
    tip: 'برای پوستر لیگ، «silhouette against spotlight» را امتحان کن.',
    prompt: `Basketball player dunking, rim and net detail, dark arena with a single spotlight, motion blur on the crowd, dramatic streetball aesthetic, high shutter sports photo, ${Q}` },
  { id: 'sp3', cat: 'sport', t: 'دوومیدانی در پیست بارانی',
    tip: 'برای تبلیغ کفش، «splash close to the shoes» بگذار.',
    prompt: `Sprinter exploding out of the blocks on a wet track, water spray, intense facial expression, side profile shot, cool overcast light, professional athletics photography, ${Q}` },
  { id: 'sp4', cat: 'sport', t: 'کوهنوردی در قله',
    tip: 'برای حس پیروزی، «arms raised, sunrise behind» را اضافه کن.',
    prompt: `Climber reaching a snowy summit at sunrise, arms raised, clouds below, frost on the jacket, epic scale, adventure sports photography, wide angle with human in lower third, ${Q}` },
  { id: 'sp5', cat: 'sport', t: 'یوگا در ساحل صبح',
    tip: 'برای کلاس آنلاین، «clean silhouette, calm mood» عالی است.',
    prompt: `Woman practicing yoga on a quiet beach at sunrise, calm sea, soft warm light, long shadow in the sand, minimalist composition, serene wellness photography, ${Q}` },

  /* ───────────── 🖌️ نقاشی ───────────── */
  { id: 'pa1', cat: 'painting', t: 'آبرنگ شهری زنده',
    tip: 'برای چاپ، «visible paper texture and bloom edges» را نگه دار.',
    prompt: `Loose urban watercolor of a busy morning market, umbrellas and bicycles, ink outlines and color blooms, visible paper texture, warm earthy palette, expressive plein air painting, ${Q}` },
  { id: 'pa2', cat: 'painting', t: 'امپرسیونیست دریایی',
    tip: 'برای بافت ضخیم، «palette knife strokes» را اضافه کن.',
    prompt: `Impressionist oil painting of sailboats on a windy bay, thick impasto brushwork, lavender and turquoise reflections, radiant afternoon light, Monet inspired composition, gallery canvas, ${Q}` },
  { id: 'pa3', cat: 'painting', t: 'نقاشی ژاپنی سومیه',
    tip: 'برای فضای خالی هنری، «generous empty space, red seal stamp» را اضافه کن.',
    prompt: `Sumi-e ink painting of bamboo swaying in the wind, bold expressive strokes, dry brush texture on rice paper, single small bird, red seal stamp, minimalist Japanese aesthetic, ${Q}` },
  { id: 'pa4', cat: 'painting', t: 'هنر دیجیتال مفهومی',
    tip: 'برای کانسپت آرت بازی، «mood-driven silhouette storytelling» بگذار.',
    prompt: `Concept art of a lonely traveler crossing a vast salt flat at dusk, tiny figure against immense landscape, painterly digital brushwork, moody teal and orange palette, cinematic storytelling, ${Q}` },
  { id: 'pa5', cat: 'painting', t: 'هنر خط و هندسه',
    tip: 'برای چاپ پوستر مینیمال، «limited palette, bold graphic shapes» عالی است.',
    prompt: `Minimal abstract art: bold black arcs and one red circle over textured beige plaster, subtle grain, mid-century modern print aesthetic, balanced geometric composition, ${Q}` },

  /* ───────────── 🏠 معماری ───────────── */
  { id: 'ar1', cat: 'arch', t: 'ویلای مدرن کنار دریاچه',
    tip: 'برای بنر املاک، «warm interior lights at dusk» حس دلچسبی می‌دهد.',
    prompt: `Modern glass villa on a calm lake shore at blue hour, warm interior lighting, wooden deck, still water reflections, architectural photography, ultra wide symmetrical composition, ${Q}` },
  { id: 'ar2', cat: 'arch', t: 'دکوراسیون داخلی مینیمال',
    tip: 'برای فروشگاه مبلمان، «morning sunlight, linen fabrics» اضافه کن.',
    prompt: `Minimal japandi living room, low linen sofa, oak coffee table, paper lantern, single branch in a ceramic vase, morning light and long shadows, interior design photography, ${Q}` },
  { id: 'ar3', cat: 'arch', t: 'آشپزخانه‌ی سنگی مدرن',
    tip: 'برای کابینت‌ساز، «marble veining close-up detail» اضافه کن.',
    prompt: `Modern kitchen with a marble waterfall island, matte black fixtures, brass pendant lights, warm wood cabinetry, soft daylight from a large window, high end interior photography, ${Q}` },
  { id: 'ar4', cat: 'arch', t: 'نماهای بتنی و نور',
    tip: 'برای نمونه‌کار معماری، «strong diagonal shadows» بگذار.',
    prompt: `Brutalist concrete building facade with rhythmic geometric openings, strong diagonal sunlight and shadows, clear blue sky, minimal skyline, fine art architectural photography, ${Q}` },
  { id: 'ar5', cat: 'arch', t: 'رستوران دنج شبانه',
    tip: 'برای صفحه‌ی رزرو، «ambient candlelight, blurred diners» را امتحان کن.',
    prompt: `Cozy restaurant interior at night, exposed brick and warm pendant lights, vintage wooden tables, greenery, blurred diners, inviting atmosphere, editorial hospitality photography, ${Q}` },

  /* ───────────── 📚 کتاب کودک ───────────── */
  { id: 'ki1', cat: 'kidsbook', t: 'روباه کوچک و فانوس',
    tip: 'برای کتاب چاپی، «flat colors, no harsh shadows» مناسب چاپ است.',
    prompt: `Children's book illustration of a small fox carrying a lantern through a snowy pine forest, friendly owl above, soft blue night, warm lantern glow, gentle textures, whimsical hand drawn style, ${Q}` },
  { id: 'ki2', cat: 'kidsbook', t: 'کشتی‌سوار کاغذی',
    tip: 'برای کتاب داستان، شخصیت را در چند صحنه با همین سبک تکرار کن.',
    prompt: `Charming illustration of a boy sailing a paper boat on a puddle river between giant dandelions, bright primary colors, playful perspective, storybook page composition with soft margins, ${Q}` },
  { id: 'ki3', cat: 'kidsbook', t: 'شهر ساخته‌شده از شیرینی',
    tip: 'برای جلد کتاب، «centered hero and empty sky for the title» بگذار.',
    prompt: `Whimsical illustration of a candy village made of cake houses and lollipop trees, children riding a spoon sled, pastel palette, cozy storybook charm, wide composition for a book cover, ${Q}` },
  { id: 'ki4', cat: 'kidsbook', t: 'ماه و ستاره‌های بامزه',
    tip: 'برای پوستر اتاق کودک، «large moon in upper third» عالی است.',
    prompt: `Sleepy crescent moon with a soft blanket of clouds, smiling stars wearing tiny hats, deep night blue with warm yellow glow, gentle bedtime illustration, soothing and calm, ${Q}` },
  { id: 'ki5', cat: 'kidsbook', t: 'هیولای مهربان زیر تخت',
    tip: 'برای آموزش کودکان، هیولا را کاملاً بی‌آزار و بامزه نگه دار.',
    prompt: `Friendly fuzzy monster peeking from under a child's bed, wearing slippers and holding a flashlight, warm nightlight, playful and reassuring mood, cute children's illustration style, ${Q}` },

  /* ───────────── 📊 اینفوگرافیک ───────────── */
  { id: 'in1', cat: 'infographic', t: 'اینفوگرافیک سه‌مرحله‌ای',
    tip: 'متن را بعداً در فتوشاپ فارسی کن؛ ساختار و آیکون‌ها آماده است.',
    prompt: `Clean three step infographic layout with isometric icons, flat pastel colors, numbered circles, lots of white space, modern presentation design, subtle shadows, organized grid, ${Q}` },
  { id: 'in2', cat: 'infographic', t: 'داشبورد داده مدرن',
    tip: 'برای نمونه‌کار UI، «dark mode dashboard» را امتحان کن.',
    prompt: `Modern analytics dashboard UI concept, colorful line and bar charts, KPI cards, soft shadows, rounded corners, light gray background, professional product design mockup, ${Q}` },
  { id: 'in3', cat: 'infographic', t: 'نمودار سه‌بعدی خلاقانه',
    tip: 'برای ارائه‌ی مالی، رنگ‌های سازمانی خودت را جایگزین کن.',
    prompt: `Creative 3D infographic of rising bars made of stacked coins, a small figure climbing with an arrow, gradient teal to violet, soft studio lighting, presentation graphic design, ${Q}` },
  { id: 'in4', cat: 'infographic', t: 'فرایند کار تیمی',
    tip: 'برای اسلاید آموزشی، «timeline layout, five milestones» بگذار.',
    prompt: `Flat illustration of a five step workflow timeline, tiny characters interacting with icons, muted brand palette, generous white space, corporate explainer graphic style, ${Q}` },
  { id: 'in5', cat: 'infographic', t: 'مقایسه‌ی قبل و بعد',
    tip: 'برای صفحه‌ی فروش محصول، «split screen with center divider» عالی است.',
    prompt: `Before and after comparison graphic, split screen with a vertical divider, dull gray left side and vibrant colorful right side, clean icons and arrows, marketing design, ${Q}` },

  /* ───────────── 🎨 متفرقه ───────────── */
  { id: 'mi1', cat: 'misc', t: 'چیدمان مسطح ابزار کار',
    tip: 'این سبک برای پست اینستاگرام و تامنیل یوتیوب بی‌نظره.',
    prompt: `Knolling flat lay of creative tools: camera, notebook, pencils, coffee cup, watch, on a warm concrete surface, top down, even soft light, tidy grid arrangement, muted palette, ${Q}` },
  { id: 'mi2', cat: 'misc', t: 'کتابخانه‌ی جادویی',
    tip: 'برای پوستر کتاب‌خوانی، «ladder and floating dust» اضافه کن.',
    prompt: `Endless magical library with towering bookshelves, spiral staircases, warm golden lamps, floating dust, a cat sleeping on a stack of books, cozy fantasy atmosphere, cinematic depth, ${Q}` },
  { id: 'mi3', cat: 'misc', t: 'کارگاه سازنده‌ی محتوا',
    tip: 'برای کاور پادکست، «microphone in foreground, bokeh lights behind» بگذار.',
    prompt: `Content creator's desk at night: microphone, ring light, camera on tripod, plants, moody purple and warm lamp lighting, cozy productive atmosphere, cinematic lifestyle photography, ${Q}` },
  { id: 'mi4', cat: 'misc', t: 'چای‌خانه‌ی بارانی',
    tip: 'برای اسلاید آرامش، «rain streaks on window, warm interior» را نگه دار.',
    prompt: `Cozy tea house seen through a rain covered window, warm interior glow, steam rising from cups, silhouettes of guests, autumn leaves outside, cinematic storytelling mood, ${Q}` },
  { id: 'mi5', cat: 'misc', t: 'مینیاتور شهر آینده',
    tip: 'برای تامنیل، «tilt shift miniature effect» حس ماکت می‌دهد.',
    prompt: `Tiny futuristic city diorama on a wooden table, monorail loop, glowing towers, miniature trees, tilt-shift effect, soft studio light, playful handmade model aesthetic, ${Q}` },
  { id: 'mi6', cat: 'misc', t: 'کلاژ خیابانی رنگارنگ',
    tip: 'برای پوستر رویداد هنری، «torn paper edges» را اضافه کن.',
    prompt: `Urban collage art of a city skyline made from torn paper, halftone dots and graffiti textures, bold red and blue accents, layered depth, contemporary graphic poster style, ${Q}` },
];

module.exports = { CATEGORIES, PROMPTS };
